### ISSUE TITLE
Todo checklist

### ISSUE THREAD

**Issue by Shumaister** [MatiasVillanueva97/Bio#1]
- [x]  Completar conclusiones del punto 1
- [x]  Completar conclusiones del punto 2
- [x]  Completar conclusiones del punto 3
- [x]  Completar conclusiones del punto 4
- [x]  Completar conclusiones del punto 5

**Comment by Shumaister** [comment]
Listo, con la subida del punto 6 se cierra el issue
